service: serverless-podcast

frameworkVersion: "=1.4.0"

custom: ${file(config.yml)}

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: eu-central-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:ListObjects
        - s3:PutObject
      Resource: arn:aws:s3:::${self:custom.bucket}

functions:
  generateFeed:
    handler: handler.generateFeed
    events:
      - s3:
        bucket: ${self:custom.bucket}
        event: s3:*
        rules:
          - suffix: .mp3
    environment:
      BUCKET: ${self:custom.bucket}
      TITLE: ${self:custom.title}
      LINK: ${self:custom.link}
      DESCRIPTION: ${self:custom.description}
      LANGUAGE: ${self:custom.language}
      AUTHOR: ${self:custom.author}
      KEYWORDS: ${self:custom.keywords}
      EXCPLICIT: ${self:custom.explicit}
      IMAGE_URL: ${self:custom.imageURL}
      EMAIL: ${self:custom.email}
      CATEGORY: ${self:custom.category}
      SUB_CATEGORIES: ${self:custom.subcategories}
      BASE_URL: ${self:custom.baseURL}
