service: serverless-podcast

frameworkVersion: "=1.4.0"

custom:
  bucket: ${file(config.${opt:stage, self:provider.stage}.yml):bucket}

provider:
  name: aws
  runtime: nodejs4.3
  stage: prod
  region: eu-central-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
        #- s3:ListObjects
        #- s3:HeadObject
        #- s3:PutObject
      Resource:
        - arn:aws:s3:::${self:custom.bucket}
        - arn:aws:s3:::${self:custom.bucket}/*

functions:
  generateFeed:
    handler: handler.generateFeed
    events:
      - s3:
        bucket: ${self:custom.bucket}
        event: s3:*
        rules:
          - suffix: .mp3
    environment:
      STAGE: ${opt:stage, self:provider.stage}
